### ISSUE TITLE
typo in xample usage

### ISSUE THREAD

**Issue by Kikubernetes** [mandorra/multishell-qspace-gradients#7]
Hi,
Thank you for creating nice tool!

There seems a typo in xample usage. N_b0 may come before 'interspersed'(True or False)?
I have changed it like
```
python qspaceweight.py samples.txt siemens.dvs debug.txt  5 True 1000 2000 3000
```
and it worked!

**Comment by mandorra** [comment]
Hi @Kikubernetes, you're right. First the number of B0's and then the boolean to indicate if they need to be interspersed. I'll change it in the readme.

**Comment by Kikubernetes** [comment]
Thank you for quick response！👍
